[package]
name = "todos"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.0.30"
pretty_env_logger = "0.4.0"
log = "0.4.14"
tokio = { version = "1", features = ["full"] }
actix-web = "4.2.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
